env:
  node: true
  es6: true
  mocha: true
globals:
  d3: true

extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - warn
  no-alert:
    - warn
