language: node_js
dist: trusty
sudo: required
node_js: 6
script: npm test
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
    - aprilweb@gmail.com
deploy:
  provider: npm
  email: germanattanasio@gmail.com
  api_key: "${npm_api_key}"
  skip_cleanup: true
  on:
    tags: true
    repo: personality-insights/sunburst-chart
